/*
**  GSC-18128-1, "Core Flight Executive Version 6.7"
**
**  Copyright (c) 2006-2019 United States Government as represented by
**  the Administrator of the National Aeronautics and Space Administration.
**  All Rights Reserved.
**
**  Licensed under the Apache License, Version 2.0 (the "License");
**  you may not use this file except in compliance with the License.
**  You may obtain a copy of the License at
**
**    http://www.apache.org/licenses/LICENSE-2.0
**
**  Unless required by applicable law or agreed to in writing, software
**  distributed under the License is distributed on an "AS IS" BASIS,
**  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
**  See the License for the specific language governing permissions and
**  limitations under the License.
*/

/*
** File: cfe_tbl_task.c
**
** Subsystem: cFE TBL Task
**
** Author: David Kobe (the Hammers Company, Inc.)
**
** Notes:
**
*/


/*
** Required header files
*/
#include "private/cfe_private.h"
#include "cfe_version.h"
#include "cfe_tbl_internal.h"
#include "cfe_tbl_events.h"
#include "cfe_tbl_msg.h"
#include "cfe_tbl_task_cmds.h"
#include "cfe_tbl_verify.h"
#include "cfe_msgids.h"
#include <string.h>

#include "cfe_sb_eds.h"

/*
** Table task global data
*/
CFE_TBL_TaskData_t    CFE_TBL_TaskData;


/* CFE TABLE EDS - The content of this file is generated by the build scripts */
#include "cfe_tbl_eds_dictionary.h"
#include "cfe_tbl_eds_dispatcher.h"

/*
** Table task const data
*/
/*
 * Define a lookup table for TBL command codes
 */
static const CFE_TBL_Application_Component_Telecommand_DispatchTable_t CFE_TBL_TC_DISPATCH_TABLE =
{
        .CMD =
        {
                .AbortLoad_indication = CFE_TBL_AbortLoadCmd,
                .Activate_indication = CFE_TBL_ActivateCmd,
                .DeleteCDS_indication = CFE_TBL_DeleteCDSCmd,
                .Dump_indication = CFE_TBL_DumpCmd,
                .DumpRegistry_indication = CFE_TBL_DumpRegistryCmd,
                .Load_indication = CFE_TBL_LoadCmd,
                .Noop_indication = CFE_TBL_NoopCmd,
                .ResetCounters_indication = CFE_TBL_ResetCountersCmd,
                .SendRegistry_indication = CFE_TBL_SendRegistryCmd,
                .Validate_indication = CFE_TBL_ValidateCmd
        },
        .SEND_HK =
        {
                .indication = CFE_TBL_HousekeepingCmd
        }

};


/******************************************************************************/

void CFE_TBL_TaskMain(void)
{
    int32  Status;

    CFE_ES_PerfLogEntry(CFE_MISSION_TBL_MAIN_PERF_ID);

    Status = CFE_TBL_TaskInit();
    
    if(Status != CFE_SUCCESS)
    {
      CFE_ES_WriteToSysLog("TBL:Application Init Failed,RC=0x%08X\n", (unsigned int)Status);
      CFE_ES_PerfLogExit(CFE_MISSION_TBL_MAIN_PERF_ID);      
      /* Note: CFE_ES_ExitApp will not return */
      CFE_ES_ExitApp(CFE_ES_RunStatus_CORE_APP_INIT_ERROR);
    }/* end if */

    /*
     * Wait for other apps to start.
     * It is important that the core apps are present before this starts receiving
     * messages from the command pipe, as some of those handlers might depend on
     * the other core apps.
     */
    CFE_ES_WaitForSystemState(CFE_ES_SystemState_CORE_READY, CFE_PLATFORM_CORE_MAX_STARTUP_MSEC);

    /* Main loop */
    while (Status == CFE_SUCCESS)
    {
        /* Increment the Main task Execution Counter */
        CFE_ES_IncrementTaskCounter();

        CFE_ES_PerfLogExit(CFE_MISSION_TBL_MAIN_PERF_ID);

        /* Pend on receipt of packet */
        Status = CFE_SB_RcvMsg( &CFE_TBL_TaskData.MsgPtr,
                                CFE_TBL_TaskData.CmdPipe,
                                CFE_SB_PEND_FOREVER);

        CFE_ES_PerfLogEntry(CFE_MISSION_TBL_MAIN_PERF_ID);

        if (Status == CFE_SUCCESS)
        {
            /* Process cmd pipe msg */
            CFE_TBL_TaskPipe(CFE_TBL_TaskData.MsgPtr);
        }else{
            CFE_ES_WriteToSysLog("TBL:Error reading cmd pipe,RC=0x%08X\n",(unsigned int)Status);
        }/* end if */

    }/* end while */

    /* while loop exits only if CFE_SB_RcvMsg returns error */
    CFE_ES_ExitApp(CFE_ES_RunStatus_CORE_APP_RUNTIME_ERROR);

} /* end CFE_TBL_TaskMain() */


/******************************************************************************/

int32 CFE_TBL_TaskInit(void)
{
    int32 Status = CFE_SUCCESS;

    /*
    ** Register Table Services with ES
    */
    Status = CFE_ES_RegisterApp();

    if(Status != CFE_SUCCESS)
    {
      CFE_ES_WriteToSysLog("TBL:Call to CFE_ES_RegisterApp Failed:RC=0x%08X\n",(unsigned int)Status);
      return Status;
    }/* end if */

    /* Register the data dictionary so that outgoing messages can be processed by other apps */
    CFE_SB_EDS_RegisterSelf(&CFE_TBL_DATATYPE_DB);

    
    /*
    ** Initialize global Table Services data
    */
    CFE_TBL_InitData();

    /*
    ** Register event filter table
    */
    Status = CFE_EVS_Register(NULL, 0, 0);

    if(Status != CFE_SUCCESS)
    {
      CFE_ES_WriteToSysLog("TBL:Call to CFE_EVS_Register Failed:RC=0x%08X\n",(unsigned int)Status);
      return Status;
    }/* end if */
    
    /*
    ** Create Software Bus message pipe
    */
    Status = CFE_SB_CreatePipe(&CFE_TBL_TaskData.CmdPipe,
                                CFE_TBL_TaskData.PipeDepth,
                                CFE_TBL_TaskData.PipeName);
    if(Status != CFE_SUCCESS)
    {
      CFE_ES_WriteToSysLog("TBL:Error creating cmd pipe:RC=0x%08X\n",(unsigned int)Status);
      return Status;
    }/* end if */                                                                

    /*
    ** Subscribe to Housekeeping request commands
    */
    Status = CFE_SB_Subscribe(CFE_TBL_SEND_HK_MID, CFE_TBL_TaskData.CmdPipe);

    if(Status != CFE_SUCCESS)
    {
      CFE_ES_WriteToSysLog("TBL:Error subscribing to HK Request:RC=0x%08X\n",(unsigned int)Status);
      return Status;
    }/* end if */

    /*
    ** Subscribe to Table task ground command packets
    */
    Status = CFE_SB_Subscribe(CFE_TBL_CMD_MID, CFE_TBL_TaskData.CmdPipe);

    if(Status != CFE_SUCCESS)
    {
      CFE_ES_WriteToSysLog("TBL:Error subscribing to gnd cmds:RC=0x%08X\n",(unsigned int)Status);
      return Status;
    }/* end if */
    
    /*
    ** Task startup event message
    */
    Status = CFE_EVS_SendEvent(CFE_TBL_INIT_INF_EID, CFE_EVS_EventType_INFORMATION, "cFE TBL Initialized.  cFE Version %d.%d.%d.%d",
                               CFE_MAJOR_VERSION,CFE_MINOR_VERSION,CFE_REVISION,CFE_MISSION_REV);

    if(Status != CFE_SUCCESS)
    {
      CFE_ES_WriteToSysLog("TBL:Error sending init event:RC=0x%08X\n",(unsigned int)Status);
      return Status;
    }/* end if */

    return CFE_SUCCESS;

} /* End of CFE_TBL_TaskInit() */


/******************************************************************************/

void CFE_TBL_InitData(void)
{
    /* Initialize Counters */
    CFE_TBL_TaskData.CommandCounter = 0;
    CFE_TBL_TaskData.CommandErrorCounter = 0;
    CFE_TBL_TaskData.SuccessValCounter = 0;
    CFE_TBL_TaskData.FailedValCounter = 0;

    /* Get the assigned Application ID for the Table Services Task */
    CFE_ES_GetAppID(&CFE_TBL_TaskData.TableTaskAppId);

    /* Initialize Command Pipe Parameters */
    CFE_TBL_TaskData.PipeDepth = CFE_TBL_TASK_PIPE_DEPTH;
    strncpy(CFE_TBL_TaskData.PipeName, CFE_TBL_TASK_PIPE_NAME, 16);

    /* Initialize Packet Headers */
    CFE_SB_InitMsg(&CFE_TBL_TaskData.HkPacket,
                   CFE_TBL_HK_TLM_MID,
                   sizeof(CFE_TBL_TaskData.HkPacket),
                   true);

    CFE_SB_InitMsg(&CFE_TBL_TaskData.TblRegPacket,
                   CFE_TBL_REG_TLM_MID,
                   sizeof(CFE_TBL_TaskData.TblRegPacket),
                   true);

} /* End of CFE_TBL_InitData() */


/******************************************************************************/

void CFE_TBL_TaskPipe(CFE_SB_Msg_t *MessagePtr)
{
    int32 CmdStatus;

    CmdStatus = CFE_TBL_Application_Component_Telecommand_Dispatch(
            CFE_SB_Telecommand_indication_Command_ID, MessagePtr, &CFE_TBL_TC_DISPATCH_TABLE);

    if (CmdStatus == CFE_TBL_NOT_IMPLEMENTED ||
            CmdStatus == CFE_STATUS_BAD_COMMAND_CODE)
    {
        CFE_EVS_SendEvent(CFE_TBL_CC1_ERR_EID, CFE_EVS_EventType_ERROR,
                          "Invalid command code -- ID = 0x%04X, CC = %d",
                          (unsigned int)CFE_SB_MsgIdToValue(CFE_SB_GetMsgId(MessagePtr)),
                          (int)CFE_SB_GetCmdCode(MessagePtr));

        /* The error counter IS incremented for bad command codes */
        CFE_TBL_TaskData.CommandErrorCounter++;
    }
    else if (CmdStatus == CFE_STATUS_WRONG_MSG_LENGTH)
    {
        CFE_EVS_SendEvent( CFE_TBL_LEN_ERR_EID, CFE_EVS_EventType_ERROR,
                           "Invalid msg length -- ID = 0x%04X, CC = %d, Len = %d",
                           (unsigned int)CFE_SB_MsgIdToValue(CFE_SB_GetMsgId(MessagePtr)),
                           (int)CFE_SB_GetCmdCode(MessagePtr),
                           (int)CFE_SB_GetTotalMsgLength(MessagePtr));

        /* The error counter IS incremented for bad message length */
        CFE_TBL_TaskData.CommandErrorCounter++;
    }
    else if (CmdStatus == CFE_STATUS_UNKNOWN_MSG_ID)
    {
        CFE_EVS_SendEvent(CFE_TBL_MID_ERR_EID, CFE_EVS_EventType_ERROR,
                "Invalid message ID -- ID = 0x%04X",
                (unsigned int)CFE_SB_MsgIdToValue(CFE_SB_GetMsgId(MessagePtr)));

        /* The error counter IS NOT incremented for bad msg IDs */
    }
    else if (CmdStatus == CFE_TBL_INC_CMD_CTR)
    {
        CFE_TBL_TaskData.CommandCounter++;
    }
    else if (CmdStatus < 0)
    {
        /*
         * Any other code in the error domain should increment the error count.
         *
         * Note that CFE_TBL_DONT_INC_CTR is an informational code
         * and therefore in the positive range, so it will avoid this
         * increment.
         */
        CFE_TBL_TaskData.CommandErrorCounter++;
    }

} /* End of CFE_TBL_TaskPipe() */

/******************************************************************************/

/************************/
/*  End of File Comment */
/************************/

